# Пример конфигурации для Streamlit Cloud.
# Создайте в настройках секцию Secrets и перенесите значения
# в файл .streamlit/secrets.toml (файл не хранится в репозитории).

LLM_BACKEND = "gemini"
GEMINI_API_KEY = "AIzaSyBWKvvwprlwW0kv9FYC6vD0i1PAEebBbCI"
GEMINI_MODEL = "gemini-1.5-flash"
